### ISSUE TITLE
Marketplace Support

### ISSUE THREAD

**Issue by RonWalker22** [bloom-solutions/borutus#31]
## What
I'm working on a PR to be able to keep track of accounts with buyers and sellers. Multitenancy Support takes care of one party, marketplace will add support for both parties.

## How 
Very similar to how Multitenancy Support is added(updated readme below)

Marketplace Support
=====================

Borutus supports marketplace applications. This is achieved by associating all Accounts under `Borutus::Account` with a "Seller" object (typically some model in your Rails application). To add marketplace support to Borutus, you must do the following:

- [Enable Multitenancy Support](#multitenancy-support)

- Generate the migration which will add `seller_id` to the borutus accounts table

```sh
bundle exec rails g borutus:marketplace
```

- Run the migration

```sh
rake db:migrate
```

- Update the initializer, i.e. `config/initializers/borutus.rb`

```ruby
Borutus.config do |config|
  config.enable_tenancy = true
  config.tenant_class = 'Tenant'
  
  config.enable_marketplace = true
  config.seller_class = 'Seller'
end
```

*NOTE: When building entries, be sure to specify the account directly, rather than use the `account_name` feature. Otherwise you'll probably end up with the wrong account.*

```ruby
debit_account = Borutus::Account.where(name: "Cash", tenant: my_tenant, seller: my_seller).last
credit_account = Borutus::Account.where(name: "Unearned Revenue", tenant: my_tenant, seller: my_seller).last
entry = Borutus::Entry.new(
  description:  "Order placed for widgets",
  date:  Date.yesterday,
  debits: [{ account: debit_account, amount: 100.00}],
  credits: [{ account: credit_account, amount: 100.00}]
)
```

---

Any thoughts?

**Comment by ace-subido** [comment]
Hi @RonWalker22 thanks for writing the issue and pull request! 😄  Here's some of my thoughts:

- I think the concept of attaching a domain such as a `marketplace` feels out of scope in double-entry accounting. 
- `Seller` sounds like an entity that `has_many :accounts`, I feel like that's what the `tenant` concept caters to. Is `tenant` missing something that couldn't encapsulate that data? 

@ramontayag care to chime in too?

**Comment by RonWalker22** [comment]
@ace-subido you're right. I will use a separate join table instead.
