### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by kirantpatil** [bloom-solutions/borutus#35]
Hi,

Planning to add Rails 7 support ?

Thanks.

**Comment by ramontayag** [comment]
We don't have any plans to do it, but happy to accept pull requests.

**Comment by kirantpatil** [comment]
Now Plutus supports Rails 7.

@ramontayag Why don't you submit upstream pull request all the changes of borutus so that it will help everyone ?

Borutus has minor changes.

@mbulat what do you think about it ?

Thanks.

**Comment by mbulat** [comment]
@ramontayag Hello, I've just come across this fork, and have noticed that the MIT license has been altered. 

Please revert the license to include my name. BloomX can include it's copyright date for modifications after mine. 

Thank you.

**Comment by ramontayag** [comment]
Will do thanks @mbulat.

@kirantpatil I suggest submitting the PR to plutus instead

**Comment by mbulat** [comment]
Many thanks! @ramontayag

**Comment by kirantpatil** [comment]
@ramontayag Thanks for your support.

I need some time but  will do it.
