### ISSUE TITLE
Support for Vouchers

### ISSUE THREAD

**Issue by kirantpatil** [bloom-solutions/borutus#37]
Hi,

Do you have plans to introduce [Vouchers ](https://www.double-entry-bookkeeping.com/bookkeeping-basics/voucher-system-in-accounting/) ?

**Comment by ramontayag** [comment]
This and plutus are just plain double-entry ledgers. I suggest you create the voucher capability on top of something like this. You can attach items to ledger entries via the commercial document polymorphic association.

https://github.com/bloom-solutions/borutus/blob/079967de32400a4817b9e7b2f01e2312267b1f40/app/models/borutus/entry.rb#L28

**Comment by kirantpatil** [comment]
Thank a lot. I will look in to it.
